import { PublicationType, PhotoType, SocialNetworks } from "../types";

export interface DialogContentProps {
  currentStep: number;
  selectedPublicationType: PublicationType | null;
  selectedPhotoType: PhotoType | null;
  handlePublicationTypeChange: (type: PublicationType) => void;
  handlePhotoTypeChange: (type: PhotoType) => void;
  nextStep: () => void;
  facebookTemplates: any[];
  instagramTemplates: any[];
  selectedFacebookTemplateId: string | null;
  selectedInstagramTemplateId: string | null;
  setSelectedFacebookTemplateId: (id: string) => void;
  setSelectedInstagramTemplateId: (id: string) => void;
  generatedText: string;
  setGeneratedText: (text: string) => void;
  isGeneratingText: boolean;
  handleGenerateText: () => Promise<void>;
  listing: any;
  selectedFacebookImages: string[];
  setSelectedFacebookImages: (images: string[]) => void;
  selectedInstagramImages: string[];
  setSelectedInstagramImages: (images: string[]) => void;
  bannerImage: string | null;
  bannerType: "VENDU" | "A_VENDRE";
  musicList: string[];
  selectedMusic: string | undefined;
  currentlyPlaying: string | null;
  toggleFacebookImageSelection: (imageUrl: string) => void;
  toggleInstagramImageSelection: (imageUrl: string) => void;
  selectAllFacebookImages: (images: string[]) => void;
  selectAllInstagramImages: (images: string[]) => void;
  deselectAllFacebookImages: () => void;
  deselectAllInstagramImages: () => void;
  onDragEnd: (result: any) => void;
  selectBannerImage: (imageUrl: string) => void;
  handleMusicChange: (value: string) => void;
  previewMusic: (musicName: string) => void;
  setBannerType: (type: "VENDU" | "A_VENDRE") => void;
  brokerImageUrl: string | null;
  setBrokerImageUrl: (url: string | null) => void;
  agencyLogoUrl: string | null;
  setAgencyLogoUrl: (url: string | null) => void;
  brokerName: string;
  setBrokerName: (name: string) => void;
  brokerEmail: string;
  setBrokerEmail: (email: string) => void;
  brokerPhone: string;
  setBrokerPhone: (phone: string) => void;
  formErrors: {[key: string]: string};
  setFormErrors: (errors: {[key: string]: string}) => void;
  isGeneratingSlideshow: boolean;
  isGeneratingBanner: boolean;
  slideshowUrl: string | null;
  bannerUrl: string | null;
  slideshowError: string | null;
  bannerError: string | null;
  slideshowRenderId: string | null;
  bannerRenderId: string | null;
  generateSlideshow: () => Promise<string | null>;
  generateBanner: () => Promise<void>;
  refetchSlideshowStatus: () => void;
  handleRegenerateSlideshow: () => void;
  handleRegenerateBanner: () => void;
  selectedNetworks: SocialNetworks;
  setSelectedNetworks: (networks: SocialNetworks) => void;
  handleNetworkChange: (network: "facebook" | "instagram", checked: boolean) => void;
  isPublishing: boolean;
  handlePublish: () => Promise<void>;
}
