// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msmuyhmxlrkcjthugcxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zbXV5aG14bHJrY2p0aHVnY3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4ODYyMjgsImV4cCI6MjA1MjQ2MjIyOH0.Pnd3nnw-SZDHcX_neGFaKSzCnRG01bW1ANuyWVPMPUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);